apiVersion: v1
kind: Secret
metadata:
  name: common-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: "liJsuqTqRbik8RHDnDNISLlsvBhF1Lj7PhkjvoWo2mc="
  JWT_ACCESS_TOKEN_VALIDITY: "3600"
  JWT_REFRESH_TOKEN_VALIDITY: "86400"
